name: example
description: An example
version: 1.0.0
publish_to: 'none'

environment:
  sdk:
  flutter:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  dart_dependencies_report: 
    path: ../
  flutter_analysis_options:
    git: 
      url: https://github.com/defuncart/flutter_analysis_options
    version: 0.0.1

flutter:
  uses-material-design: true

dart_dependencies_report:
  title: Dependencies Report
  output_dir: ''
  output_filename: dependencies_report
  generate_pdf: true
  generate_md: true
