name: dart_dependencies_report
description: A package which generates a report of all a project's dependencies.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/defuncart/dart_dependencies_report

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  intl: ^0.16.1
  pubspec_lock: ^2.0.1
  pubspec_yaml: ^2.0.1
  pdf: 1.8.1
  web_scraper:
    git:
      url: https://github.com/defuncart/fork_web_scraper
      ref: feature/remove-dependency-on-flutter

dev_dependencies:
  test: ^1.15.0
  flutter_analysis_options:
    git: 
      url: https://github.com/defuncart/flutter_analysis_options
    version: 0.0.1
